runtime: python37
env: standard
entrypoint: gunicorn -b :$PORT app:app

runtime_config:
  python_version: 3

manual_scaling:
  instances: 1

env_variables:
  CLOUD_STORAGE_BUCKET: cs430-lily-tran

resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10
